import { DM_Sans, Exo } from "next/font/google";
import "./styles/style.css";
import "./styles/res.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
// import { LoadingProvider } from "./providers/LoadingProvider";
// import { NavigationEvents } from "./components/NavigationEvents";

const DMSans = DM_Sans({
  variable: "--main_font",
  subsets: ["latin"],
});
const ExoFont = Exo({
  variable: "--secondary_font",
  subsets: ["latin"],
});

export const metadata = {
  title: "Gwebpro Next App",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
    nocache: true,
    googleBot: {
      index: false,
      follow: false,
      noimageindex: true,
    },
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${DMSans.variable} ${ExoFont.variable}`}>
        {/* <LoadingProvider> */}
        <Header />
        {children}
        {/* <NavigationEvents /> */}
        <Footer />
        {/* </LoadingProvider> */}
      </body>
    </html>
  );
}
