name: CI/CD Pipeline (Root User)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root  # Using root directly
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /home/deploy/my-app  # Your app path
            git pull origin main
            npm install
            pm2 restart my-app
